---
# tasks file for mysql
- name: Crear la base de datos en mysql
  mysql_db: name={{ wp_mysql_db }} state=present
- name: Crear el usuario mysql
  mysql_user:
    name={{ wp_mysql_user }} 
    password={{ wp_mysql_password }} 
    priv=*.*:ALL
