---
- name: instalar apache2
  apt: name=apache2 update_cache=yes state=latest
  notify:
    - iniciar servicio de apache

- name: instalar php
  apt: name={{item}} state=latest
  with_items: 
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - git
