---
- hosts: servidores
  sudo: yes
  tasks:
    - name: quitar key
      apt_key: url=http://keyserver.ubuntu.com id=7F0CEB10 state=absent

    - name: desistalar mongodb
      apt: name=mongodb-org* state=absent purge=yes

    - name: eliminar directorios
      shell: rm -r /var/log/mongodb
      shell: rm -r /var/lib/mongodb
